version: "3"
services:
  db:
    build: ./database
    ports:
      - "3306:3306"
    volumes:
      - db_volume:/var/lib/mysql
    networks:
      - mynet

  auth_service:
    build: ./auth
    ports:
      - "5001:5001"
    networks:
      - mynet

  book_service:
    build: ./book
    ports:
      - "5002:5002"
    networks:
      - mynet

  borrow_service:
    build: ./borrow
    ports:
      - "5003:5003"
    networks:
      - mynet

  frontend:
    build: .
    ports:
      - "5000:5000"
    networks:
      - mynet

volumes:
  db_volume:

networks:
  mynet:
    driver: bridge
